version: "3"

services:
  mc:
    container_name: integration_test_server
    image: itzg/minecraft-server
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      ENABLE_COMMAND_BLOCK: "TRUE"
      ONLINE_MODE: "FALSE"
      VERSION: "1.19.4"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./minecraft-data:/data